### ISSUE TITLE
Phone log: Quick Entry

### ISSUE THREAD

**Issue by Ldhatter** [adriannadiaz/Axiona#113]
As a user, I want to have a quick entry / shortcut modal to log a phone call without losing my current work on my page.

USP [1]
Priority [Low]
Risk [Low]

Tasks:
- [x] Add modal component for add-phonelog
- [x] Edit toolbar to use modal instead of dashboard phonelog
- [x] Add pronouns dropdown
- [x] Add subject dropdown
- [x] Test

Pronoun 
```
subject = [ undisclosed, she/her, they/them, he/him ]
```

Subject
```
Housing
Medical
Legal
Accompaniment
Financial
Name Change
Food Security
Job Finding
Immigration
Victims of Violence
Sexual Health
Information 
```

**Comment by adriannadiaz** [comment]
@Ldhatter I changed some stuff here
