### ISSUE TITLE
SocialWorker Online Website

### ISSUE THREAD

**Issue by wahabwajahat** [adriannadiaz/Axiona#29]
As a social worker, I want to have access to the website anywhere.

Priority: [Med]
USP: [3]

**Comment by adriannadiaz** [comment]
UPDATE: After meeting with our Stakeholder on 30/01, it was deemed that it is not an immediate priority.

**Comment by Ldhatter** [comment]
After our meeting with ASTT(e)Q this week, let's reopen this so we can track our progress for when we meet with their IT people.

Anna-christina is the person to talk to at Cactus regarding IT related issues (but they're away until Monday).
