### ISSUE TITLE
Custom and uniform UI theme

### ISSUE THREAD

**Issue by adriannadiaz** [adriannadiaz/Axiona#43]
As a user, I want to have an easy to use, uniform in look, and intuitive application.

USP: 3
Priority: Low
Risk: Low

*Tasks:*
- [x] Create colour theme (uniform colour palette)
- [x] Implement colour theme
-  **Responsive (working for mobile)**
- [x] Change px to rem
- [x] Forms
- [x] Include icons
- [x] Replace participant avatar
- [x] Design App logo 
- [x] Design a fav.icon based on the application icon (currently the A Angular Shield is being displayed...)

*Components:*
- [x] Login
- [x] Participants
- [x] Casefiles
- [x] Notes
- [x] Docouments
- [x] Resources
- [x] Phone log
- [x] Dashboard activity
- [x] Tasks
- [x] Active case files
- [x] Users
- [x] Reports
- [x] Trashbin

Useful links:
[Google Material Color](https://material.io/color/#!/?view.left=0&view.right=0&primary.color=673AB7&secondary.color=64B5F6)
[Google Icon](https://material.io/icons)

**Comment by Ldhatter** [comment]
![screen shot 2018-03-22 at 2 51 46 pm](https://user-images.githubusercontent.com/13111600/37791995-f30cd9f6-2de0-11e8-8a67-e3aa77f841e1.png)
![screen shot 2018-03-22 at 2 53 48 pm](https://user-images.githubusercontent.com/13111600/37792003-f626b800-2de0-11e8-82c3-0f0b9b387d0f.png)
![screen shot 2018-03-22 at 2 43 31 pm](https://user-images.githubusercontent.com/13111600/37792149-64044dba-2de1-11e8-91c1-d1ae8fbc1d59.png)
![screen shot 2018-03-22 at 3 04 10 pm](https://user-images.githubusercontent.com/13111600/37792489-4f0bf736-2de2-11e8-86f9-1ad8b714ac29.png)

**Comment by Ldhatter** [comment]
@adriannadiaz @wahabwajahat @annarog in the above comment, i posted some colour swatches. any initial thoughts? things that work / things that dont?

Keep in mind we should have colours for:
- primary colour
- accent colour (ie: something to go along with the primary colour)
- warning colour (eg: for errors, unsuccessful saves, bad input etc)
- success colour (eg: correct input, successful save, completed task etc)
- "in progress" colour (? not sure what to call this, but a colour to represent something in progress, or not yet fully successful. ex: casefile in progress. Maybe we don't use this colour but it could be good!)

**Comment by Ldhatter** [comment]
APPLICATION NAME
-
@adriannadiaz @wahabwajahat @annarog we need to come up with a name that doesn't use the words _social worker_ (this a reserved professional title).

I'll start a thread in slack and we can post our final top decisions here :)

**Comment by Ldhatter** [comment]
[logo.pdf](https://github.com/adriannadiaz/SocialWorker/files/1853676/logo.pdf)

**Comment by annarog** [comment]
I like the third colour palette 👌

**Comment by Ldhatter** [comment]
Commit #73bbbf0

**Comment by Ldhatter** [comment]
Bug: Trash bin case file participant populate name
---

Display participant's name alongside their deleted case file

http://mongoosejs.com/docs/api.html#schema_Schema-post

**Comment by Ldhatter** [comment]
Bug: Active Casefiles
---
display no active casefiles
