### ISSUE TITLE
Edit Social Worker

### ISSUE THREAD

**Issue by Ldhatter** [adriannadiaz/Axiona#80]
As an admin user I want to edit other users information, and privilege access.

USP [2]
Priority [Med]

**Tasks**
- [x] Component to edit users (using Reactive form see #37 for helpful tips)
- [x]  Test

**Comment by adriannadiaz** [comment]
OMG It is sooooo good. Just place the trashcan in the bottom like we did for Participants... we don't want someone double clicking the pencil and the second click clicks on the trashcan...

![screen shot 2018-04-12 at 2 46 19 pm](https://user-images.githubusercontent.com/6773380/38697558-61a4806e-3e60-11e8-9a07-0d978ee08bf6.png)

**Comment by adriannadiaz** [comment]
@annarog

**Comment by annarog** [comment]
@adriannadiaz sounds good! I think I followed the Resource edit form, where the trashcan is also at the top. So we should fix it there too
