### ISSUE TITLE
Reports

### ISSUE THREAD

**Issue by Ldhatter** [adriannadiaz/Axiona#90]
As a user, I want to view statistical reports on application use.

See Dashboard issue #48  and also about stats in #66 
Dashboard has already several components. Implement the reports component separately. 

Reports include:
- [x] Phone log 
~- [ ] Case files Need more feedback from stakeholder~ 

USP: 5
Priority: High
Risk: Low

_Description_
Users have to able to see reports on aggregate participant data for phone logs, case files. 

 
_Scope of Work_
- [x] Uniformize the fields for phone logs (done by Liuai on a separate ticket. We want things on neat buckets for aggregation.
- [x] Research into how to get data with CSV in and out of the MongoDB application. 
- [x] Research into which modules are best suited for this task. (ChartJS)
- [x] Generate one report, by default...
~- [ ] Add GUI elements to be able to see more reports.~
- [x] Decide if we want to render all reports just by going into reports ? 

_Demo Requirements_
1. Given that there are a number of phone logs already in the system.
2. User goes into Dashboard/Reports
3. User is able to see reports with charts.

_Acceptance Criteria_

For phonelog Analysis, possible reports (discuss here which are the priorities...)
--------------------------------------------------------------------------------
- By urgency YES/no (Pie Chart)
- By pronoun {feminine, neutral, masculine, unknown} (Pie Chart)
- By caller type {trans person, organization, social worker, other person} (Pie Chart)
-By subject {depends on Resources...) (Pie Chart)
- By phone number area code (extract first threedigits) more fancy regex is required  (Pie Chart)
- By date (get range, beginning, end, plot the entries in time axis) (Bar Chart)
- By creator social worker (Pie Chart)
- By resolved (percentage) (Pie Chart)
- By resolver social worker (Pie Chart)
- By time to resolve (resolvedBy - createdAt) (Bar Chart, but more complicated)

**Comment by adriannadiaz** [comment]
TESTING @Ldhatter 
<img width="440" alt="screen shot 2018-04-16 at 9 45 27 pm" src="https://user-images.githubusercontent.com/6773380/38844055-d476ed90-41bf-11e8-9a0f-cac14d8fbb83.png">
