### ISSUE TITLE
Form Polishing 🤖

### ISSUE THREAD

**Issue by Ldhatter** [adriannadiaz/Axiona#99]
Please verify each form, their validators, and fields. Look for and fix any bugs.
Also after submitting a form (eg: for a new resource) make sure empty fields aren't being displayed.

USP: [5]
Priority: [High]

Tasks:
- [x] **Fix Form Reset** when reseting it does not reset to pristine/untouched form (ie: it shows errors)
- [x] Resources: add, edit
- [x] Participants: add, edit
- [x] Phone log: add, edit
- [x] Login
- [x] Users: add
- [x] Tasks
- [x] Casefile
- [x] All modals
- [x] Notes
- [x] Documents
- [x] Trashbin

If all goes quickly see #80 Edit Social Worker and complete this

**Comment by Ldhatter** [comment]
@wahabwajahat 

So i sent message to angular-material gitter channel to get feedback on the problems we have with form reset/submit (eg: empty fields show up as having validation errors)

i made this stackblitz so you can see the difference with/without using ngSubmit:
(Stackblitz example)[https://stackblitz.com/edit/angular-reset-example]

Will let you know if anyone says more info on it, but in the meantime i would remove ngSubmit and just use `(click)="submit()"` or alternatively whichever method the submit should be calling.

**Comment by wahabwajahat** [comment]
Thanks @Ldhatter , I will look into it! :)

**Comment by Ldhatter** [comment]
Ohhh i got more info!
someone submitted this to angular/material but it's actually a bug with angular/core.
(Issue # 44190)[https://github.com/angular/material2/issues/4190]

So ngSubmit is part of FormGroupDirective (not FormGroup). 
You can use the solution given by (willshowell)[https://github.com/angular/material2/issues/4190#issuecomment-305031716]
and (here)[https://github.com/angular/material2/issues/4190#issuecomment-305222426]

two things:
- using @ViewChild to access the FormGroupDirective
- using resetForm() instead of reset()
